flower_api_public_clients_account_show:
    path:     /accounts/{id}
    defaults: { _controller: FlowerClientsBundle:Api\Account:publicGetById }
    methods: [GET]

flower_api_public_clients_account_findall:
    path:     /accounts
    defaults: { _controller: FlowerClientsBundle:Api\Account:publicGetAll }
    methods: [GET]

flower_api_public_clients_contact_show:
    path:     /contacts/{id}
    defaults: { _controller: FlowerClientsBundle:Api\Contact:getById }
    methods: [GET]

flower_api_public_clients_contact_findall:
    path:     /contacts
    defaults: { _controller: FlowerClientsBundle:Api\Contact:getAll }
    methods: [GET]
