flower_api_clients_account_show:
    path:     /accounts/{id}
    defaults: { _controller: FlowerClientsBundle:Api\Account:getById }
    methods: [GET]

flower_api_clients_account_findall:
    path:     /accounts
    defaults: { _controller: FlowerClientsBundle:Api\Account:getAll }
    methods: [GET]
