flower_api_clients_account_show:
    path:     /accounts/{id}
    defaults: { _controller: FlowerClientsBundle:Api\Account:getById }
    methods: [GET]

flower_api_clients_account_findall:
    path:     /accounts
    defaults: { _controller: FlowerClientsBundle:Api\Account:getAll }
    methods: [GET]

flower_api_clients_account_create:
    path:     /accounts/new
    defaults: { _controller: FlowerClientsBundle:Api\Account:create }
    methods: [POST]

flower_api_clients_activity_findall:
    path:     /activity
    defaults: { _controller: FlowerClientsBundle:Api\Activity:getAll }
    methods: [GET]

flower_api_clients_subsidiary_findall:
    path:     /subsidiaries/{account}
    defaults: { _controller: FlowerClientsBundle:Api\Subsidiary:getAll }
    methods: [GET]

flower_api_clients_subsidiary_create:
    path:     /subsidiaries/new
    defaults: { _controller: FlowerClientsBundle:Api\Subsidiary:create }
    methods: [POST]
    
flower_api_clients_contact_show:
    path:     /contacts/{id}
    defaults: { _controller: FlowerClientsBundle:Api\Contact:getById }
    methods: [GET]
flower_api_clients_contact_create:
    path:     /contacts/new
    defaults: { _controller: FlowerClientsBundle:Api\Contact:create }
    methods: [POST]

flower_api_clients_contact_findall:
    path:     /contacts
    defaults: { _controller: FlowerClientsBundle:Api\Contact:getAll }
    methods: [GET]
flower_api_clients_contact_findallbyaccount:
    path:     /contacts/account/{accountId}
    defaults: { _controller: FlowerClientsBundle:Api\Contact:getByAccount }
    methods: [GET]
