services:
#    flower_core.example:
#        class: Flower\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    form.type.contact:
        class: Flower\ClientsBundle\Form\Type\ContactType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: contact_type }
    form.api.type.contact:
        class: Flower\ClientsBundle\Form\Type\Api\ContactType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: contact_type }
    form.type.callevent:
        class: Flower\ClientsBundle\Form\Type\CallEventType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: contact_type }
    form.type.account:
        class: Flower\ClientsBundle\Form\Type\AccountType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: contact_type }
    client.service.excelexport:
        class: Flower\ClientsBundle\Service\ExcelExportService
        arguments: ['@service_container']
    client.service.account:
        class: Flower\ClientsBundle\Service\AccountService
        arguments: ['@service_container']
    client.service.callevent:
        class: Flower\ClientsBundle\Service\CallEventService
        arguments: ['@service_container']