<?php

namespace Flower\ClientsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{
    
    public function search($completeText, $texts, $limit = 10)
    {
        $qb = $this->createQueryBuilder("a");
        $qb->orWhere("a.name like :text")
              ->orWhere("a.phone like :text")
              ->setParameter("text", "%".$completeText."%");
        $qb->setMaxResults($limit);
        $result = $qb->getQuery()->getResult();
        $count = 0;
        foreach ($texts as $text) {
            $qb->orWhere("a.name like :text_".$count)
                ->orWhere("a.phone like :text_".$count)
                ->setParameter("text_".$count, "%".$text."%");
            $qb->setMaxResults($limit);
            $count ++;
        }
        $result = array_merge($result,$qb->getQuery()->getResult());
        return array_unique($result, SORT_REGULAR);
    }
    public function findByBoard($board){
        $qb = $this->createQueryBuilder("a");
        $qb->join("a.boards","b");
        $qb->where("b.id = :board")->setParameter("board", $board->getId());
        $querry = $qb->getQuery();
        return $querry->getOneOrNullResult();
    }
}