<?php

namespace Flower\ClientsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CallEventStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallEventStatusRepository extends EntityRepository
{
}
