<?php

namespace Flower\ClientsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CallEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallEventRepository extends EntityRepository
{
	function getPlannerQuery($limit = 20,$offset = 0){
		$qb = $this->createQueryBuilder("ce");
		$em = $this->getEntityManager();
		$query = $em->createQuery(
			'SELECT a, max(ce.date) as maxDate, date_diff( max(ce.date), CURRENT_DATE()) as diff FROM FlowerModelBundle:Clients\Account a 
			 LEFT JOIN FlowerModelBundle:Clients\CallEvent ce WITH ce.account = a.id
			 LEFT JOIN FlowerModelBundle:Clients\CallEventStatus ces WITH ce.status = ces.id
			 WHERE ce.id is null or ces.finished = 1
			 group by a.id ');
		$query->setMaxResults($limit);
		$query->setFirstResult($offset);
        
        return $query->getResult();

		
	}
}
