<?php

namespace Flower\ClientsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
	public function search($completeText, $texts, $limit = 10)
    {
        $qb = $this->createQueryBuilder("n");
        $qb->orWhere("n.title like :text")
              ->orWhere("n.body like :text")
              ->setParameter("text", "%".$completeText."%");
        $qb->setMaxResults($limit);
        $result = $qb->getQuery()->getResult();
		$count = 0;
        foreach ($texts as $text) {
            $qb->orWhere("n.title like :text_".$count)
                ->setParameter("text_".$count, "%".$text."%");
            $qb->setMaxResults($limit);
            $count ++;
        }
        $result = array_merge($result,$qb->getQuery()->getResult());
        return array_unique($result, SORT_REGULAR);
    }

}