<?php

namespace Flower\ClientsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubsidiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubsidiaryRepository extends EntityRepository
{

    public function getByAccountQuery($accountId)
    {
        $qb = $this->createQueryBuilder("s");
        $qb->select("s");
        $qb->join("s.account", "a");
        $qb->where("a.id = :account_id");
        $qb->orderBy("s.name");
        $qb->setParameter("account_id", $accountId);
        return $qb;
    }

}
